import { jsxRenderer, useRequestContext } from "hono/jsx-renderer";

// The gold "b"/keyhole Bedini mark used in the top bar.
function BrandMark() {
  return (
    <svg viewBox="354 198 826 826" width="22" height="22" aria-hidden="true">
      <path
        fill="#dfa84d"
        d="m 711.66835,872.99998 c 3.12201,-23.1657 11.09937,-46.12048 16,-69 1.46942,-6.86041 6.76904,-19.09814 5.09644,-25.90662 -1.50892,-6.14227 -14.52741,-12.99939 -18.77082,-18.09338 -12.12585,-14.55664 -16.99048,-34.55664 -13.89044,-53 10.90753,-64.89276 100.36621,-71.84222 126.25232,-14 9.20502,20.56848 5.51764,47.25726 -8.21606,65 -4.45978,5.7616 -18.8736,13.46875 -20.42896,20.10419 -1.7478,7.45648 3.89636,19.52612 5.53314,26.89581 4.99829,22.505 12.47028,45.1246 15.42438,68 18.98541,-7.8939 36.17273,-18.6945 50.99615,-33.0394 59.99115,-58.05429 58.10553,-151.33456 4.28858,-211.95675 -12.5893,-14.18122 -29.06506,-25.81061 -46.28473,-33.6952 -41.2962,-18.90875 -90.55969,-17.78167 -131,2.95063 -14.19116,7.27533 -25.10822,21.26233 -39,27.74072 v -118 -30 c 0,-3.41217 -1.12671,-9.39642 1.02777,-12.30096 2.96234,-3.99366 12.42621,-5.78229 16.97223,-7.35492 16.85065,-5.82929 34.35736,-9.75556 52,-12.21375 76.08026,-10.60052 156.83405,9.39575 218,56.52088 31.11003,23.96856 56.51985,53.26428 75.99925,87.34875 18.221,31.88263 30.018,66.63275 35.0008,103 4.8841,35.64667 3.4091,71.87659 -4.6513,107 -6.45,28.10614 -17.6297,55.1477 -32.2098,80 -80.5748,137.34262 -262.26554,178.89272 -399.13895,104.6913 -75.61722,-40.9933 -131.29803,-116.6485 -145.56482,-201.6913 -8.28381,-49.37897 -4.43518,-101.06879 -4.43518,-151 v -213 -121 c 0,-19.87366 -2.27722,-41.2981 0.28937,-61 2.85763,-21.93604 22.1492,-39.00476 44.71063,-36.8302 13.24054,1.27624 26.15982,5.66321 38,11.58325 10.36578,5.18286 20.4837,11.41699 29,19.33649 15.90561,14.79095 28.95416,32.91626 35.27853,53.91046 10.00504,33.2124 4.72147,72.65924 4.72147,107 v 253 c 0,69.30634 -12.22061,147.17615 43,199.9606 13.68964,13.0858 29.60394,20.2983 46,29.0394 z"
      />
    </svg>
  );
}

// Root document chrome, wrapping every page's content.
export const renderer = jsxRenderer(({ children }) => {
  const c = useRequestContext();
  const q = c.req.query("q") ?? "";
  return (
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="/tsgit.css" />
        <script src="/app.js" defer></script>
      </head>
      <body>
        <div class="cg-shell">
          <header class="cg-header">
            <div class="cg-header-inner">
              <a class="cg-brand" href="/">
                <BrandMark />
                <span class="cg-wordmark">tsgit</span>
                <span class="cg-cursor" aria-hidden="true"></span>
              </a>
              <div class="cg-spacer"></div>
              <form class="cg-search" action="/" method="get" role="search">
                <svg
                  class="icon"
                  viewBox="0 0 24 24"
                  width="15"
                  height="15"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                >
                  <circle cx="11" cy="11" r="7"></circle>
                  <path d="m21 21-4.3-4.3"></path>
                </svg>
                <input type="search" name="q" value={q} placeholder="search repositories…" autocomplete="off" />
              </form>
            </div>
          </header>
          <main class="cg-main">{children}</main>
          <footer class="cg-footer">
            <div class="cg-footer-inner">
              <span>
                generated by <span class="accent">tsgit</span>
              </span>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
});

// Repo header band + tab strip. Reads the discovered repo and the active page
// straight off the request context, so handlers never thread navigation state
// through render props.
function RepoHeader() {
  const c = useRequestContext();
  const disc = c.get("disc");
  // No repo resolved (e.g. an error or 404 under /:repo/*): skip the band.
  if (!disc) return null;
  const name = disc.name;
  const path = c.req.path;
  const active =
    path.includes("/tree/") || path.includes("/raw/")
      ? "tree"
      : path.endsWith("/log/")
        ? "log"
        : "summary"; // summary, commit and diff all sit under the summary tab

  const tab = (page: "summary" | "log" | "tree", href: string) => (
    <a class={`cg-tab${active === page ? " active" : ""}`} href={href}>
      {page}
    </a>
  );

  return (
    <>
      <div class="cg-repohead">
        <div>
          <div class="cg-crumb">
            <a href="/">~</a>
            <span class="slash">/</span>
            <span class="name">{name}</span>
          </div>
          {disc.description ? <p class="desc">{disc.description}</p> : null}
        </div>
      </div>
      <nav class="cg-tabs">
        {tab("summary", `/${name}/`)}
        {tab("log", `/${name}/log/`)}
        {tab("tree", `/${name}/tree/`)}
      </nav>
    </>
  );
}

// Nested layout for repo pages: wraps the parent chrome and prepends the band.
export const repoLayout = jsxRenderer(({ children, Layout }) => (
  <Layout>
    <RepoHeader />
    {children}
  </Layout>
));
